/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/shoe.gltf 
*/

import React, { useContext } from "react";
import { useGLTF } from "@react-three/drei";
import { ShoeContext } from "../context/ShoeContextProvider";

export function Shoe(props) {
    const { nodes, materials } = useGLTF("./models/shoe.gltf");

    const { mesh, stripes, sole, laces, caps, inner, band, patch } =
        useContext(ShoeContext);
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.shoe.geometry}>
                {" "}
                <meshStandardMaterial color={laces} />
            </mesh>
            <mesh geometry={nodes.shoe_1.geometry}>
                {" "}
                <meshStandardMaterial color={mesh} />
            </mesh>
            <mesh geometry={nodes.shoe_2.geometry}>
                {" "}
                <meshStandardMaterial color={caps} />
            </mesh>
            <mesh geometry={nodes.shoe_3.geometry}>
                {" "}
                <meshStandardMaterial color={inner} />
            </mesh>
            <mesh geometry={nodes.shoe_4.geometry}>
                {" "}
                <meshStandardMaterial color={sole} />
            </mesh>
            <mesh geometry={nodes.shoe_5.geometry}>
                {" "}
                <meshStandardMaterial color={stripes} />
            </mesh>
            <mesh geometry={nodes.shoe_6.geometry}>
                {" "}
                <meshStandardMaterial color={band} />
            </mesh>
            <mesh geometry={nodes.shoe_7.geometry}>
                {" "}
                <meshStandardMaterial color={patch} />
            </mesh>
        </group>
    );
}

useGLTF.preload("./models/shoe.gltf");
